[package]
name = "acm_rust"
version = "0.1.0"
authors = ["Nils Olsson <nilso@enosis.net>"]
edition = "2018"

[dependencies]
common_macros = "0.1.1"
clap = { version = "2.33.0", features = ["yaml"] }

[package.metadata.docs.rs]
rustdoc-args = [ "--html-in-header", "katex-header.html" ]
